name: Android CI

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'WaterTracker Debug build to distribute on Firebase app distribution'
        description: 'Release Notes'
      version_name:
        type: number
        required: true
        default: '1.0'
        description: 'Version Name (e.g., 1.0)'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Configure Git
      run: |
              git config --local user.name "GitHub Actions Bot"
              git config --local user.email "actions@github.com"

    - name: Check Git Remote
      run: git remote -v

    - name: Check Branch Tracking
      run: git branch -vv

    - name: Check Git Status
      run: git status    
