name: Water Tracker android app deploy to firebase app distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'WaterTracker Debug build to distribute on Firebase app distribution'
        description: 'Release Notes'
      version_name:
        type: number
        required: true
        default: 1.0
        description: 'Version Name (e.g., 1.0)'

job:
    build: # Defines a job named 'build'
      name: Building and distributing app on Debug variant # Sets a display name for the job
      runs-on: ubuntu-latest # Specifies that the job will run on the latest version of Ubuntu

      steps:
        - uses: actions/checkout@v2 # Checkout the repository

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'gradle'

        - name: Grant execute permission for gradlew
          run: Chmod +x gradlew

        - name: Run unit tests
          run: ./gradlew clean testDebug
